### PR TITLE
Add *bsd support

### PR DESCRIPTION
**Pull request by nunotexbsd**
Successfully tested on FreeBSD / rust 1.65.0
- needed superuser pevileges to run

https://github.com/orf/gping/issues/88

### CODE REVIEW

**Comment by orf** [comment]
Thank you @nunotexbsd! Is there a simple way we can detect if we're running as a superuser, and bail out on BSD?

I'll merge this as-is, and we can think about that later maybe.

**Comment by nunotexbsd** [comment]
> Thank you @nunotexbsd! Is there a simple way we can detect if we're running as a superuser, and bail out on BSD?
> 
> I'll merge this as-is, and we can think about that later maybe.

Well, not sure if I understand it but superuser permission is by default root user in *nix and linux.
What programs like sudo and doas do is to give regular users root permission to execute certain commands not available for regular users.
Some examples on FreeBSD and maybe *bsd:
- if a user don't belongs to group wheel he can't change to root with su cmd.
- doas and sudo after configured gives root permissions for regular users
A particular case when bsd ping needs root permission to execute:
```
-f	     Flood ping.  Outputs packets as fast as they come back or one
	     hundred times per second, whichever is more.  For every
	     ECHO_REQUEST sent a period	"." is printed,	while for every
	     ECHO_REPLY	received a backspace is	printed.  This provides	a
	     rapid display of how many packets are being dropped.  **Only the
	     super-user	may use	this option.**
```
The reason why gping only runs on super-user mode maybe related to what gping is trying to access on FreeBSD.
Other possibility is bsd rust code implementation causing this.

I've just gave random ideas around this permission problem with hope to getting some conlusion.

Hope that helps

**Comment by orf** [comment]
Ok, it's fine, we can figure it out later. I'm happy to merge this, but you're missing the contents of `tests/bsd.txt`. If you're ok to add that with the following value:

```
PING google.com (216.58.198.174): 56 data bytes
64 bytes from 216.58.198.174: icmp_seq=0 ttl=116 time=35.034 ms
64 bytes from 216.58.198.174: icmp_seq=1 ttl=116 time=35.266 ms
64 bytes from 216.58.198.174: icmp_seq=2 ttl=116 time=35.204 ms
64 bytes from 216.58.198.174: icmp_seq=3 ttl=116 time=34.941 ms
64 bytes from 216.58.198.174: icmp_seq=4 ttl=116 time=35.617 ms
ping: sendto: Network unreachable

-----

None
35.034ms
35.266 ms
35.204 ms
34.941 ms
35.617 ms
None
```

then perfect. If you could include a line that is outputted when BSD ping times out, that would also be good. I don't have BSD installed to test on, so I can't get this output.

If you'd rather I add this to your MR then I can do it for you, just let me know. I'm aiming to do a release today

**Comment by nunotexbsd** [comment]
Please add what's needed to my MR because I'm not very confortable with those patches.
You can test bsd easily within a VM: https://download.freebsd.org/releases/VM-IMAGES/13.1-RELEASE/amd64/Latest/

Thanks

**Comment by orf** [comment]
I'd really not like to have to download and configure a VM just to run `ping`. can't you just tell me what the error line is when a ping times out?

Looking at [the source (?)](https://github.com/openbsd/src/blob/master/sbin/ping/ping.c) it seems that it's similar to inetutils in that it doesn't output anything during a timeout. This means we can't support it, unfortunately.

**Comment by orf** [comment]
Hey,
I've added support here: https://github.com/orf/gping/pull/235

**Comment by nunotexbsd** [comment]
Thanks, I will work on freebsd port tomorow.

**Pull request closed without merging**
