### PR TITLE
Support pinging multiple hosts

### PR DESCRIPTION
**Pull request by SOF3**
Usage: `gping 1.1.1.1 8.8.8.8`

image

### CODE REVIEW

**Comment by orf** [comment]
This is amazing, thank you so much! Are you going to add colours as part of this PR?

**Comment by SOF3** [comment]
There seems to be a bit trouble adding colors. I just realized `tui::widgets::Chart` only supports one style per chart instead of one style per dataset, so this might not be easy to fix.

**Comment by SOF3** [comment]
Never mind, I was blind. https://docs.rs/tui/0.13.0/tui/widgets/struct.Dataset.html#method.style

**Comment by SOF3** [comment]
Fixed colors. The choice of using grey for the first choice might not be great, but I'm not good at UX so I'm just using `Color::Indexed(i)` for now; if you have a better priority list for colors, please change it.

**Comment by orf** [comment]
Thank you! I'm thinking we can do `Color:Indexed(i + 1)` to avoid grey, because it doesn't look good. I'll check this out and merge it today 👍

**Comment by SOF3** [comment]
Don't forget to update the `--help` message in the readme. I am not including it into this pull request since `-b` also seems to be missing on master.

**Comment by orf** [comment]
There are some conflicts due to the other MRs, I'll have some time to resolve these this evening and merge 👍

**Comment by orf** [comment]
Thank you so much for this @SOF3!

**Comment by SOF3** [comment]
There seems to be an offset in x coordinate as the process runs for long.
image

**Comment by SOF3** [comment]
After running really long, it will end up like this
image

**Comment by SOF3** [comment]
I guess I should file an issue

**Pull request merged**
